### ISSUE TITLE
Consolidate people data

### ISSUE THREAD

**Issue by lukefretwell** [distributedgov/distributedgov.github.io#17]
I'm pulling people data from two sources, which isn't great:

* https://github.com/distributedgov/distributedgov.github.io/blob/master/_data/people.yml
* https://github.com/distributedgov/distributedgov.github.io/tree/master/_people

I'd like to consolidate (ideally using the latter approach), but am not sure why some of the files aren't pulling from a single source (hint: I think it's because I'm not coding correctly).

Places where I'm pulling this data:

* https://github.com/distributedgov/distributedgov.github.io/blob/master/_includes/people.html
* https://github.com/distributedgov/distributedgov.github.io/blob/master/_layouts/people.html
* https://github.com/distributedgov/distributedgov.github.io/blob/master/_layouts/post.html
* https://github.com/distributedgov/distributedgov.github.io/blob/master/_layouts/default.html

**Comment by lukefretwell** [comment]
via Janette:

> try {% for author in site.data.people %}

**Comment by brianseek** [comment]
@lukefretwell here is a PR for this one: https://github.com/distributedgov/distributedgov.github.io/pull/25

It also adds the multi-author functionality since the fix for this and that were touching the same areas and had a lot to do with each other.

The concept of multiple authors as been applied everywhere. So you can decide to use it on anything. To add more than one author, update you frontmatter to be like:
```
author:
  - lukefretwell
  - tonycooper
```

If you only have a single author the string version still works:
```
author: lukefretwell
```

I added comments on most of the code, let me know if you have any questions or if any thing looks off.
